image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - lint
  - build

lint:
  tags:
    - docker
  stage: lint
  script: "npm run lint"

build:
  tags:
    - docker
  stage: build
  script: "npm run quicktestbuild"