image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install

stages:
  - lint
  - test
  - build

lint:
  tags:
    - docker
  stage: lint
  script: "npm run lint"


test:
  tags:
    - docker
  stage: test
  script: "npm run test -- --no-color"
  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 30 days

build:
  tags:
    - docker
  stage: build
  script: "npm run build"