image: node:alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - usr/bin/
    - /var/cache/apk/

before_script:
  - npm ci --cache .npm --prefer-offline

stages:
  - lint
  - test
  - build

lint:
  tags:
    - docker
  stage: lint
  script: "npm run lint"


test:
  tags:
    - docker
  stage: test
  script: "apk add chromium && CHROME_BIN=/usr/bin/chromium-browser npm run test -- --singleRun true"
  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 30 days

build:
  tags:
    - docker
  stage: build
  script: "npm run build"